// Builds fragcount.html and fragcount-mobile.html from an unsaved MediaWiki parse of Template_FragCalc.wikitext, and checks
// the draft on the way. Read-only: sends the draft to action=parse; no login, tokens or edits.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const dir = path.dirname(fileURLToPath(import.meta.url));
const read = name => fs.readFileSync(path.join(dir, name), 'utf8');
const wiki = 'https://bluearchive.wiki';
const headers = {'User-Agent': 'ba-wiki-widgets FragCalc preview builder'};

async function parse(params) {
    const body = new URLSearchParams({action: 'parse', format: 'json', formatversion: '2', contentmodel: 'wikitext', prop: 'text|parsewarnings', ...params});
    const result = await (await fetch(wiki + '/w/api.php', {method: 'POST', body, headers})).json();
    assert(!result.error && !result.warnings, JSON.stringify(result));
    assert.deepEqual(result.parse.parsewarnings, []);
    assert(!/class="error"/.test(result.parse.text), result.parse.text.slice(0, 2000));
    return result.parse;
}

// A stylesheet as TemplateStyles serves it. The sanitizer drops what it doesn't support without an error: every declaration
// has to come through
async function sanitize(title, css) {
    const {text: html} = await parse({title: 'Shiroko', text: `<templatestyles src="${title}" />`,
        templatesandboxtitle: title, templatesandboxcontentmodel: 'sanitized-css', templatesandboxtext: css});
    const sanitized = html.match(/<style[^>]*>([\s\S]*?)<\/style>/)[1];
    const declarations = text => text.replace(/\/\*[\s\S]*?\*\//g, '').match(/[a-z-]+\s*:[^;{}]+(?=[;}])/g).map(x => x.replace(/\s/g, ''));
    const kept = new Set(declarations(sanitized));
    assert.deepEqual(declarations(css).filter(x => !kept.has(x)), [], `TemplateStyles dropped or changed declarations of ${title}`);
    console.log(`${title}: TemplateStyles validation passed.`);
}

// Images as MobileFrontend's mobile view serves them: the image in noscript, then a placeholder that it loads when it comes into
// view. The markup of the wiki's mobile pages on 2026-09-30; the parse API doesn't apply this transform.
const lazyImages = html => html.replace(/<img\b([^>]*?)\s*\/?>/g, (tag, attributes) => {
    const [src, alt, width, height, srcset, css] = ['src', 'alt', 'width', 'height', 'srcset', 'class']
        .map(name => (attributes.match(new RegExp(`\\s${name}="([^"]*)"`)) || [])[1]);
    return `<noscript>${tag}</noscript><span class="lazy-image-placeholder" style="width: ${width}px;height: ${height}px;" data-mw-src="${src}"`
        + (alt === undefined ? '' : ` data-alt="${alt}"`) + ` data-width="${width}" data-height="${height}"`
        + (srcset ? ` data-mw-srcset="${srcset}"` : '') + ` data-class="${css}"> </span>`;
});

// The wiki's paths, for pages opened from disk
const absolute = html => html
    .replace(/(href|src)="\/\//g, '$1="https://')
    .replace(/(href|src)="\/(?!\/)/g, `$1="${wiki}/`)
    .replace(/srcset="([^"]+)"/g, (_, value) => 'srcset="' + value.replace(/(^|, )\/\//g, '$1https://') + '"');

// Template:FragCalc. The wiki has neither it nor its stylesheet yet, so it's parsed without its templatestyles tag. It uses the
// wiki's Template:Rank, whose stylesheet comes with the parse.
const fragCalc = read('Template_FragCalc.wikitext').replace(/<templatestyles [^>]*\/>\n?/, '');
const invocation = "{{FragCalc|eleph=Shiroko's Eleph}}";
const {text: fragCalcHtml, categories} = await parse({title: 'Shiroko', text: invocation, prop: 'text|parsewarnings|categories',
    templatesandboxtitle: 'Template:FragCalc', templatesandboxtext: fragCalc});
assert(!fragCalcHtml.includes('Icon_Error.png'), 'An ItemCard found no item');
assert.equal((fragCalcHtml.match(/class="fragcalc-tier"/g) || []).length, 5);
assert.equal((fragCalcHtml.match(/class="ba-template-rank/g) || []).length, 9 + 2);
assert(/<style[^>]*>[^<]*\.ba-template-rank\b/.test(fragCalcHtml), "Template:Rank's stylesheet didn't come with the parse");
// The gadget loads on the pages of the tracking category
assert.deepEqual(categories.map(category => category.category), ['Pages_with_FragCalc']);
console.log('Template:FragCalc: unsaved parse passed.');
await sanitize('Template:FragCalc/styles.css', read('style.css'));

const preview = (title, content) => `<!doctype html>
<!-- Generated by build-preview.mjs from an unsaved parse of ${invocation} on bluearchive.wiki.
     Add ?nojs to see the table without the script, or, served over http, ?gadget to run it as the wiki runs the gadget. -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${title}</title>
<link rel="stylesheet" href="style.css">
<style>
/* A stand-in for the wiki's skin (Vector legacy): its wikitable, and the DarkMode extension's inversion */
body { margin: 24px auto; padding: 0 20px; max-width: 960px; font: 14px/1.6 sans-serif; color: #202122; background: #fff; }
a { color: #36c; text-decoration: none; }
.wikitable { background-color: #f8f9fa; color: #202122; margin: 1em 0; border: 1px solid #a2a9b1; border-collapse: collapse; }
.wikitable > * > tr > th, .wikitable > * > tr > td { border: 1px solid #a2a9b1; padding: 0.2em 0.4em; }
.wikitable > * > tr > th { background-color: #eaecf0; text-align: center; }
.wikitable > caption { font-weight: bold; }
img { border: 0; vertical-align: middle; }
.preview-toolbar { font-size: 13px; color: #54595d; }
html.skin-theme-clientpref-night { background: #fff; filter: invert(1) hue-rotate(180deg); }
html.skin-theme-clientpref-night img:not(.mw-invert), html.skin-theme-clientpref-night .mw-no-invert:not(.mw-invert) { filter: invert(1) hue-rotate(180deg); }
</style>
</head>
<body>
<p class="preview-toolbar"><label><input type="checkbox" id="preview-dark"> Dark mode (the wiki's DarkMode inversion)</label></p>
${content.trim()}
<script>
document.getElementById('preview-dark').addEventListener('change', function () {
    document.documentElement.classList.toggle('skin-theme-clientpref-night', this.checked);
});
</script>
<script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
<script>
// The script as a plain one, or as ResourceLoader runs a gadget's: in a function of its own, given jQuery
const query = new URLSearchParams(location.search);
if (query.has('gadget')) {
    fetch('fragcount.js').then(response => response.text()).then(code => Function('$', 'jQuery', code)(jQuery, jQuery));
} else if (!query.has('nojs')) {
    const script = document.createElement('script');
    script.src = 'fragcount.js';
    document.body.appendChild(script);
}
</script>
</body>
</html>
`;
fs.writeFileSync(path.join(dir, 'fragcount.html'), preview('FragCalc preview', absolute(fragCalcHtml)));
fs.writeFileSync(path.join(dir, 'fragcount-mobile.html'), preview('FragCalc preview, mobile view', lazyImages(absolute(fragCalcHtml))));
console.log('Built fragcount.html and fragcount-mobile.html');
